#ifndef _STATUS_H_
#define _STATUS_H_

#define STATUS DWORD
#define SUCCESS 0
#define NULL_POINTER_ERROR 1
#define CONNEXION_ERROR (1<<1)
#define FILE_ERROR (1<<2)
#define COMUNICATION_ERROR (1<<3)

//Particual status
#define SUCCESS_LOGIN 0
#define FAILED_LOGIN_WRONG_CREDENTIALS (1 | (1<<4))
#define FAILED_LOGIN_SERVER_REFUSED_CONNECTION (1 | (1<<5))

#define ON_SUCCESS_LOGIN(a) ((a) == SUCCESS_LOGIN)
#define ON_REFUSED_CONNECTION(a) ((a) & FAILED_LOGIN_SERVER_REFUSED_CONNECTION == FAILED_LOGIN_SERVER_REFUSED_CONNECTION)
#define ON_WRONG_CREDENTIALS(a) ((a) & FAILED_LOGIN_WRONG_CREDENTIALS == FAILED_LOGIN_WRONG_CREDENTIALS)

#define PERMISED_LOGIN_MESSAGE "OK"
#define REFUSED_BY_WRONG_CREDENTIALS_MESSAGE "N1"
#define REFUSED_BY_SERVER_REFUSED_CONNECTION_MESSAGE "N2"

#define VALID_USER 0
#define WRONG_CREDENTIALS (1<<4)
typedef struct
{
	int size;
	char buffer[4096];
} PACKAGE, *PPACKAGE;
#endif //_STATUS_H_